export const MOTIVATIONAL_PHRASES = [
  // Bienestar general (1-35)
  "Tu salud es tu mayor tesoro. Hoy es un buen día para cuidarte.",
  "Cada pequeño paso cuenta en tu camino hacia el bienestar.",
  "La constancia es la clave para una vida saludable.",
  "Cuida tu cuerpo, es el único lugar que tienes para vivir.",
  "Hoy es una nueva oportunidad para sentirte mejor.",
  "El bienestar no es un destino, es un viaje diario.",
  "Pequeños hábitos diarios construyen grandes resultados.",
  "Tu cuerpo escucha todo lo que tu mente dice, háblale con amor.",
  "La prevención de hoy es la salud del mañana.",
  "Invierte en tu salud, es el mejor activo que posees.",
  "Tu cuerpo es tu templo, cuidarlo hoy es tu mejor inversión para el mañana.",
  "Un descanso bien merecido es productivo, no perezoso.",
  "La hidratación es el combustible de tu energía diaria.",
  "Respira profundo y deja que la calma llene tu ser.",
  "El movimiento es medicina para tu cuerpo y mente.",
  "Tu bienestar empieza con decisiones pequeñas cada día.",
  "La paciencia contigo mismo es parte del proceso de sanación.",
  "Celebrar pequeños avances mantiene la llama de la esperanza.",
  "Escucha a tu cuerpo; te habla en cada latido.",
  "La gratitud transforma lo que tienes en suficiente.",
  "Un paso hoy es progreso mañana.",
  "Tu fuerza no está en lo que haces, sino en cómo persistes.",
  "La salud florece donde la intención y la acción se encuentran.",
  "Cada sorbo de agua es un regalo a tus células.",
  "Tu mente tranquila cultiva un cuerpo sano.",
  "La autocuración comienza con el respeto por tu ser.",
  "Hoy elige nutrir tu cuerpo con intención.",
  "Un corazón agradecido late con más vitalidad.",
  "Tu energía es sagrada; cuida su fuente.",
  "La serenidad del momento crea sanación duradera.",
  "Avanza a tu ritmo; tu salud no es una carrera.",
  "Cada amanecer trae una nueva oportunidad de equilibrio.",
  "Nutrir tu cuerpo es honrar tu existencia.",
  "La calma interior es la base de la recuperación total.",
  "Tu bienestar merece prioridad, no perfección.",
  "Respira, confía, y permite que tu cuerpo guíe.",
  "La fortaleza nace de la constancia, no de la urgencia.",
  "Cada elección consciente suma a tu salud futura.",
  "Tu vitalidad florece cuando la alimentas con intención.",
  "El silencio del alma nutre la medicina más poderosa.",
  "Pequeños cambios hoy construyen grandes transformaciones.",

  // Recuperación y sanación (36-70)
  "Cada día de recuperación es una victoria silenciosa.",
  "La sanación es un arte; cada célula es un lienzo.",
  "Tu proceso de sanación es único y valioso.",
  "La paciencia es tu aliada en el camino a la salud.",
  "Cada paso hacia adelante suma a tu bienestar.",
  "Tu cuerpo tiene la sabiduría de curarse; confía.",
  "La recuperación es un viaje, no un destino.",
  "Cada respiración profunda lleva vitalidad a tu ser.",
  "Tu resiliencia hoy construye tu salud mañana.",
  "La calma activa tus circuitos de sanación natural.",
  "Cada día es una nueva página en tu historia de salud.",
  "Tu capacidad de sanar es más grande que imaginas.",
  "La esperanza enciende la chispa de la recuperación.",
  "Cada pequeño avance es un regalo a tu bienestar.",
  "Tu cuerpo merece descanso y nutrientes.",
  "La recuperación consciente transforma el sufrimiento.",
  "Cada sorbo de agua pura limpia tu sistema.",
  "Tu mente curativa está disponible en cada momento.",
  "La movida suave activa la energía sanadora.",
  "Cada pensamiento positivo nutre tus células.",
  "Tu proceso de sanación es perfecto tal como es.",
  "La naturaleza brinda remedios a tu bienestar.",
  "Cada día trae nuevas posibilidades de mejorar.",
  "Tu vitalidad se renueva con cada elección consciente.",
  "La gratitud multiplica las señales de recuperación.",
  "Cada pausa es un regalo a tu sistema nervioso.",
  "Tu camino a la salud es único y válido.",
  "La intención curativa guía cada aspecto de ti.",
  "Cada noche de sueño profundo renueva tu ser.",
  "Tu poder de sanación interior es ilimitado.",
  "La respiración consciente activa tu energía vital.",
  "Cada alimento elegido con cuidado nutre tu recuperación.",
  "Tu fuerza crece al honrar tus necesidades.",

  // Motivación para cuidado médico (71-100)
  "Tu salud es prioridad; cuidarte no es egoísmo.",
  "Cada consulta médica es un paso hacia la claridad.",
  "Tu voz interior es tu mejor guía en el cuidado.",
  "La prevención hoy evita complejidad mañana.",
  "Cada medicamento tomado con intención es autocuración.",
  "Tu compromiso contigo mismo inspira bienestar.",
  "La honestidad sobre síntomas acelera la recuperación.",
  "Cada registro médico es un mapa a tu mejor salud.",
  "Tu agradecimiento por la atención médica multiplica guías.",
  "Cada día de seguimiento es un acto de amor propio.",
  "Tu camino a la salud es hoy, no mañana.",
  "La esperanza viva en cada cita médica importante.",
  "Cada pregunta a tu médico abre puertas a sanar.",
  "Tu constancia en el tratamiento es valentía.",
  "La confianza en tu equipo médico multiplica resultados.",
  "Cada cuidado preventivo es inversión en futuro.",
  "Tu compromiso con tu salud es admirable.",
  "Cada dosis con cumplimiento es autocuidado.",
  "La paciencia con tu tratamiento crea transformación.",
  "Cada registro de síntomas te acerca a la claridad.",
  "Tu determinación por sentirte mejor es inspiradora.",
  "La gratitud por tu médico multiplica sanación.",
  "Cada día de adherencia es un triunfo silencioso.",
  "Tu bienestar merece cada paso que das.",
  "Cada descanso es productivo, no perezoso.",
  "La esperanza activa cada célula curativa.",
  "Cada elección saludable hoy multiplica vitalidad.",
  "Tu proceso de mejora es único y valioso.",
  "Cada día es una nueva oportunidad de equilibrio.",
  "La vitalidad florece con intención diaria.",
  "Cada respiración es una promesa de renovación.",
  "Tu camino hacia la salud es hoy, no mañana.",
  "La gratitud transforma lo que tienes en suficiente.",
  "Cada pequeño avance merece celebración.",
  "Tu bienestar es una historia escrita cada día.",
  "La calma interior nutre tu capacidad de sanar.",
  "Cada elección consciente suma a tu futuro.",
  "Tu fuerza nace de la constancia, no la urgencia.",
];